server: 
  port: 8001
 
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/kb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
     username: root
     password: luo520
     driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  application:
     name: springcloud_demo_emp  
       
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7008.com:7008/eureka
  instance:    
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true   