server: 
  port: 8001
 
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/kb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
     username: root
     password: luo520
     driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  application:
     name: springcloud-demo-emp  
       
eureka:
  client:
    service-url:
      defaultZone: http://emp1.com:7001/eureka/,http://emp2.com:7002/eureka/
  instance:    
    instance-id: springcloud_demo_emp_8001
    prefer-ip-address: true   