server: 
  port: 8001
 
spring:
  datasource:
     url: jdbc:mysql://localhost/kb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
     username: root
     password: luo520
     driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  application:
     name: springcloud_demo_emp  
       
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka