server: 
  port: 80
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/kb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
     username: root
     password: luo520
     driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
springcloud-demo-emp: 
  ribbon: 
     MaxAutoRetriesNextServer: 0 
     MaxAutoRetries: 0  
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone:  http://localhost:7001/eureka/,http://localhost:7002/eureka/