server: 
  port: 8003
 
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/kb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
     username: root
     password: luo520
     driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  application:
     name: rabbitTest
  rabbitmq:
     host: 47.107.55.207
     username: admin
     password: 123456
  cloud:
    stream:
      bindings:
        output:
          destination: hello.new
          content-type: application/json
          
eureka:
  client:
    service-url:
      defaultZone: http://emp1.com:7001/eureka/,http://emp2.com:7002/eureka/
  instance:    
    instance-id: rabbitTest
    prefer-ip-address: true   